-- Persist the fields used by the Goods Return Note (GRTN) workflow.
ALTER TABLE IF EXISTS "ReturnNote"
  ADD COLUMN IF NOT EXISTS "siteId" TEXT,
  ADD COLUMN IF NOT EXISTS "siteName" TEXT,
  ADD COLUMN IF NOT EXISTS "subLevel" TEXT,
  ADD COLUMN IF NOT EXISTS "destinationType" TEXT,
  ADD COLUMN IF NOT EXISTS "destinationId" TEXT,
  ADD COLUMN IF NOT EXISTS "destinationName" TEXT,
  ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN IF NOT EXISTS "requestedBy" TEXT;

ALTER TABLE IF EXISTS "ReturnNoteItem"
  ADD COLUMN IF NOT EXISTS "unit" TEXT,
  ADD COLUMN IF NOT EXISTS "availableStock" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "reason" TEXT,
  ADD COLUMN IF NOT EXISTS "condition" TEXT;
